import { SlArrowRight } from "react-icons/sl";
export const categories = [
  { key: "all", label: "All Products", icon: <SlArrowRight /> },
  { key: "beauty", label: "Beauty" },
  { key: "fragrances", label: "Fragrances" },
  { key: "furniture", label: "Furniture" },
  { key: "groceries", label: "Groceries" },
  { key: "home-decoration", label: "Home Decoration" },
  { key: "kitchen-accessories", label: "Kitchen Accessories" },
  { key: "laptops", label: "Laptops" },
  { key: "mens-shirts", label: "Men's Shirts" },
  { key: "mens-shoes", label: "Men's Shoes" },
  { key: "mens-watches", label: "Men's Watches" },
  { key: "mobile-accessories", label: "Mobile Accessories" },
  { key: "motorcycle", label: "Motorcycle" },
  { key: "skin-care", label: "Skin Care" },
  { key: "smartphones", label: "Smartphones" },
  { key: "sports-accessories", label: "Sports Accessories" },
  { key: "sunglasses", label: "Sunglasses" },
  { key: "tablets", label: "Tablets" },
  { key: "tops", label: "Tops" },
  { key: "vehicle", label: "Vehicle" },
  { key: "womens-bags", label: "Women's Bags" },
  { key: "womens-dresses", label: "Women's Dresses" },
  { key: "womens-jewellery", label: "Women's Jewellery" },
  { key: "womens-shoes", label: "Women's Shoes" },
  { key: "womens-watches", label: "Women's Watches" },
];